#!/usr/bin/env fish

set -l config_dir ~/.config/herbstluftwm
set -l terminal st -f 'Inconsolata Nerd Font:size=10'
# this is a simple config for herbstluftwm

herbstclient emit_hook reload

# remove all existing keybindings
herbstclient keyunbind --all

# keybindings
set -l Mod Mod4 # Use the super key as the main modifier
herbstclient keybind $Mod-Shift-q quit
herbstclient keybind $Mod-Shift-r reload
herbstclient keybind $Mod-Shift-c close

# Keybindings to start applications
herbstclient keybind $Mod-Shift-p spawn $config_dir/restartpanels.fish
herbstclient keybind $Mod-Return spawn $terminal
herbstclient keybind $Mod-d spawn $config_dir/dmenu_run_hlwm -i
herbstclient keybind $Mod-e spawn $FILE_MANAGER
herbstclient keybind $Mod-c spawn google-chrome-stable
herbstclient keybind $Mod-b spawn $BROWSER
herbstclient keybind $Mod-Control-c spawn clipper
herbstclient keybind $Mod-l spawn slock
herbstclient keybind $Mod-Print spawn scrot
herbstclient keybind $Mod-Alt-r spawn $config_dir/scratchpad.fish calculator gnome-calculator
herbstclient keybind $Mod-Alt-Return spawn $config_dir/scratchpad.fish terminal $terminal
herbstclient keybind $Mod-Control-Pause spawn fish -c sts

# Keybindings to change keyboard layouts
herbstclient keybind $Mod-Control-d spawn setxkbmap -layout de -variant nodeadkeys -option caps:none
herbstclient keybind $Mod-Control-g spawn setxkbmap -layout gb -option caps:none

herbstclient set default_frame_layout 3

# tags
herbstclient rename default 1
for tag_name in (seq 9)
    herbstclient add $tag_name
    set -l key $tag_name
    herbstclient keybind "$Mod-$key" use $tag_name
    herbstclient keybind "$Mod-Shift-$key" move $tag_name
end

# move windows
herbstclient keybind $Mod-Control-Right move_index +1
herbstclient keybind $Mod-Control-Left move_index -1

# cylce through tags
herbstclient keybind $Mod-Right use_index +1 --skip-visible
herbstclient keybind $Mod-Left use_index -1 --skip-visible

# layouting
herbstclient keybind $Mod-r remove
#herbstclient keybind $Mod-space cycle_layout 1
herbstclient keybind $Mod-v split vertical 0.5
herbstclient keybind $Mod-h split horizontal 0.5
herbstclient keybind $Mod-s floating toggle
herbstclient keybind $Mod-f fullscreen toggle
herbstclient keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
herbstclient keybind $Mod-space                                          \
        or , and . compare tags.focus.curframe_wcount = 2                \
                 . cycle_layout +1 vertical horizontal max vertical grid \
           , cycle_layout +1

# resizing
set -l resizestep 0.01
herbstclient keybind $Mod-Control-Shift-Left resize left +$resizestep
herbstclient keybind $Mod-Control-Shift-Down resize down +$resizestep
herbstclient keybind $Mod-Control-Shift-Up resize up +$resizestep
herbstclient keybind $Mod-Control-Shift-Right resize right +$resizestep

# mouse
herbstclient mouseunbind --all
herbstclient mousebind $Mod-Button1 move
herbstclient mousebind $Mod-Button2 zoom
herbstclient mousebind $Mod-Button3 resize

# focus
herbstclient keybind $Mod-Tab cycle_all +1
herbstclient keybind $Mod-Shift-Tab cycle_all -1
herbstclient keybind $Mod-i jumpto urgent
herbstclient keybind $Mod-BackSpace cycle_monitor
herbstclient keybind $Mod-Shift-Left shift left
herbstclient keybind $Mod-Shift-Down shift down
herbstclient keybind $Mod-Shift-Up shift up
herbstclient keybind $Mod-Shift-Right shift right

# Layout
herbstclient attr theme.tiling.reset 1
herbstclient attr theme.floating.reset 1
herbstclient set always_show_frame 1
herbstclient set frame_gap 0
herbstclient set frame_padding 2
herbstclient set frame_bg_transparent 1
herbstclient set frame_transparent_width 2
herbstclient set smart_frame_surroundings 1
herbstclient set window_gap -2
herbstclient set smart_window_surroundings 0
herbstclient set mouse_recenter_gap 0

# theme
herbstclient set frame_border_active_color '#222222'
herbstclient set frame_border_normal_color '#101010'
herbstclient set frame_border_width 1
herbstclient set frame_bg_normal_color '#565656'
herbstclient set frame_bg_active_color '#345F0C'

herbstclient attr theme.active.color '#9fbc00'
herbstclient attr theme.normal.color '#454545'
herbstclient attr theme.urgent.color orange
herbstclient attr theme.inner_width 1
herbstclient attr theme.inner_color black
herbstclient attr theme.border_width 3
herbstclient attr theme.floating.border_width 4
herbstclient attr theme.floating.outer_width 1
herbstclient attr theme.floating.outer_color black
herbstclient attr theme.active.inner_color '#3E4A00'
herbstclient attr theme.active.outer_color '#3E4A00'
herbstclient attr theme.background_color '#141414'

# rules
herbstclient unrule -F
herbstclient rule focus=on # focus new clients

herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
herbstclient rule windowtype~'_NET_WM_WINDOW_TPYE_(FULLSCREEN|FS)' fullscreen=on
herbstclient rule title='gnome-calculator' pseudotile=on
herbstclient rule title='Connect to MySQL Server' pseudotile=on
herbstclient rule class='qemu-system-x86_64' tag=7 fullscreen=on

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here
herbstclient detect_monitors

# set -lx monitor_count (herbstclient get_attr monitors.count)
# tags other monitor
# if test $monitor_count -gt 1
#     set -l tag_names (seq -f '%0.fr' 9)

#     for key in (seq 9)
#         herbstclient add $tag_names[$key]
#         herbstclient keybind $Mod-Alt-$key use $tag_names[$key]
#         herbstclient keybind $Mod-Alt-Shift-$key move $tag_names[$key]
#     end
# end

# unlock, just to be sure
herbstclient unlock

# find the panel
set -l panel $config_dir/panel.fish
for monitor in (herbstclient list_monitors | cut -d: -f1)
    # start it on each monitor
    fish $panel $monitor &
end

